tracerUIFile = 'Resources/TracerGUI/tracerwindow.ui'
mainUIFile = 'Resources/gui.ui'
parametersUIFile = 'Resources/GUIViews/ParametersView/parametersview.ui'
tableUIFile = 'Resources/GUIViews/BatchTableView/batchtableview.ui'
magmapUIFile = 'Resources/GUIViews/MagnificationMapView/magnificationmapview.ui'
modeldialogUIFile = 'Resources/GUIViews/ConfigureModelsDialog/configuremodelsdialog.ui'