#!/bin/sh
#Black        0;30     Dark Gray     1;30
#Red          0;31     Light Red     1;31
#Green        0;32     Light Green   1;32
#Brown/Orange 0;33     Yellow        1;33
#Blue         0;34     Light Blue    1;34
#Purple       0;35     Light Purple  1;35
#Cyan         0;36     Light Cyan    1;36
#Light Gray   0;37     White         1;37


RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color


while getopts ":fdc" opt; do
	  case ${opt} in
	      d )       sphinx-apidoc -o docs/source src/app/ -f
			cd docs
			make html
			echo "Documentation Generated"
			cd ..
	            ;;
	      f )     cd src/app
		      python setup.py build_ext --inplace -f
		      cd ../../spark_impl
		      sbt assembly
		      sbt eclipse
		      cd ..
		      echo "\n\n\n${GREEN}Build Done${NC}\n"
	            ;;
	      c )     cd src/app
		      python setup.py build_ext --inplace
		      cd ../../spark_impl
		      sbt assembly
                      cd ../..
		      echo "\n\n\n${GREEN}Build Done${NC}\n"
	            ;;
	     \? ) echo "Usage: cmd [-d] Docs [-f] Force compile [-c] Regular compile"
	            ;;
	  esac
done


if [ ! -f .custom_preferences.json ]; then
    echo "${RED}Build Preferences not found. ${NC}"
    echo "${ORANGE}Using default parameters. To edit default, edit '.custom_preferences.json' in the project's root directory${NC}"
    cat .default_preferences.json > .custom_preferences.json
fi
